package Orelly;

import java.util.Arrays;

public class PrintingValuesWithAccessMethods {
    public static void main (String[] args){
        System.out.println (new historyMaker());
    }
    // public class HistoryMaker{ //When we print an instance without the toString method, the output will be
        //random code generated by the JVM. The toString method is also known as the method that reveals the state
        //(instance variables) of an object.
    //    private final String name = "Nelson Mandela";
    //    private final String profession = "president";

  //  }
    static class historyMaker{
        private final String name = "Nelson Mandela";
        private final String profession = "president";
        public String toString(){ //When we wanna use toString, is necessary to follow this structure.
            return name + ":" + profession;
        }
    }

}
